version: "3"
services:

  web:
    image: nginx:1.19.9
    container_name: web
    hostname: web
    restart: unless-stopped
    volumes:
      - /home/tim/web/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - home-web

  homeassistant:
    image: homeassistant/home-assistant:2021.4.4
    container_name: homeassistant
    hostname: homeassistant 
    network_mode: host
    depends_on:
      - transmission
      - deconz
      - influxdb
      - grafana
      - telegraf
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8123"]
      interval: 5s
      timeout: 3s
      retries: 100
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/ttyAMA0
    volumes:
      - /home/tim/homeassistant/config:/config

  deconz:
    image: marthoc/deconz:amd64-2.10.04 
    container_name: deconz
    hostname: deconz 
    network_mode: host
    restart: unless-stopped
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - TZ=Europe/Amsterdam
      - DECONZ_UPNP=0
      - DECONZ_DEVICE=/dev/ttyACM0 
    devices:
     - /dev/ttyACM0
    volumes:
      - /home/tim/deconz/config:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro

  influxdb:
    image: influxdb:1.8.5 
    container_name: influxdb 
    restart: unless-stopped
    hostname: influxdb
    environment:
      - INFLUXDB_DB=home_assistant
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    volumes:
      - /home/tim/influxdb:/var/lib/influxdb
      - /home/tim/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:7.5.7  
    container_name: grafana
    hostname: grafana
    user: 0:0
    depends_on:
      - telegraf
    restart: unless-stopped
    volumes:
      - /home/tim/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - home-web

  telegraf:
    image: telegraf:1.17.2 
    container_name: telegraf
    hostname: telegraf
    privileged: true
    depends_on:
      - influxdb
    restart: unless-stopped
    links:
      - influxdb
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_MOUNT_PREFIX=/hostfs
      - TELEGRAF_DB_PASSWORD=${TELEGRAF_DB_PASSWORD}
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  transmission:
    image: linuxserver/transmission:3.00-r2-ls82 
    container_name: transmission
    hostname: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - /home/tim/transmission/data:/config
      - /home/tim/ext-hd/transmission/downloads:/downloads
      - /home/tim/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - home-web

  sonarr:
    image: linuxserver/sonarr:3.0.6.1196-ls100 
    container_name: sonarr
    hostname: sonarr
    depends_on:
      - jackett
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/sonarr/data:/config
      - /home/tim/ext-hd/sonarr/tvseries:/tv
      - /home/tim/ext-hd/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - home-web
  
  radarr:
    image: linuxserver/radarr:3.0.2.4552-ls97 
    container_name: radarr
    hostname: radarr
    depends_on:
      - jackett
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/radarr/data:/config
      - /home/tim/ext-hd/radarr/movies:/movies
      - /home/tim/ext-hd/transmission/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - home-web

  jackett:
    image: linuxserver/jackett:v0.17.848-ls26 
    container_name: jackett
    hostname: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/jackett/data:/config
      - /home/tim/ext-hd/transmission/watch:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - home-web

  plex:
    image: linuxserver/plex:1.22.1.4275-48e10484b-ls39 
    container_name: plex
    hostname: plex
    network_mode: host
    depends_on:
      - sonarr
      - radarr
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/tim/plex/data:/config
      - /home/tim/ext-hd/sonarr/tvseries:/tv
      - /home/tim/ext-hd/radarr/movies:/movies
      - /tmp/transcoding:/tmp/transcoding
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.8 
    user: "0"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8380:80/tcp
      - 443:443/tcp
    environment:
      - TZ=Netherlands/Amsterdam
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=pihole.home
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - /home/tim/pihole/etc-pihole/:/etc/pihole/
      - /home/tim/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    networks:
      - home-web

networks:
  home-web:
