version: "3"
services:

  web:
    image: lscr.io/linuxserver/swag:1.32.0-ls163
    container_name: web
    hostname: web
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - URL=timsdomain.duckdns.org
      - VALIDATION=duckdns
      - SUBDOMAINS=wildcard
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /home/tim/swag:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - home-web

  authelia:
    image: ghcr.io/authelia/authelia:4.37.5
    container_name: authelia
    hostname: authelia
    depends_on:
      - web
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/authelia:/config
    networks:
      - home-web

  duckdns:
    image: lscr.io/linuxserver/duckdns:445a951b-ls110
    container_name: duckdns
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Amsterdam
      - TOKEN=${DUCKDNS_TOKEN}
      - SUBDOMAINS=timsdomain
    restart: unless-stopped
    networks:
      - home-web

  homeassistant:
    image: homeassistant/home-assistant:2023.6.1
    container_name: homeassistant
    hostname: homeassistant 
    network_mode: host
    depends_on:
      - web
      - transmission
        #      - deconz
      - influxdb
      - grafana
      - telegraf
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8123"]
      interval: 5s
      timeout: 3s
      retries: 100
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/ttyAMA0
      - /dev/ttyACM0
    volumes:
      - /home/tim/homeassistant/config:/config

  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb 
    restart: unless-stopped
    hostname: influxdb
    depends_on:
      - web
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=home-assistant
    volumes:
      - /home/tim/influxdb2:/var/lib/influxdb2
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    hostname: grafana
    user: 0:0
    depends_on:
      - web
      - telegraf
    restart: unless-stopped
    volumes:
      - /home/tim/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - home-web

  telegraf:
    image: telegraf:1.26.3 
    container_name: telegraf
    hostname: telegraf
    user: telegraf:998
    privileged: true
    depends_on:
      - web
      - influxdb
    restart: unless-stopped
    links:
      - influxdb
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_MOUNT_PREFIX=/hostfs
      - TELEGRAF_INFLUXDB_TOKEN=${TELEGRAF_INFLUXDB_TOKEN}
      - TELEGRAF_INFLUXDB_ORG=${TELEGRAF_INFLUXDB_ORG}
      - TELEGRAF_INFLUXDB_BUCKET=${TELEGRAF_INFLUXDB_BUCKET}
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  transmission:
    image: linuxserver/transmission:3.00-r2-ls111
    container_name: transmission
    hostname: transmission
    depends_on:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - /home/tim/transmission/data:/config
      - /home/tim/nas/media/transmission/downloads:/downloads
      - /home/tim/nas/media/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - home-web

  sonarr:
    image: linuxserver/sonarr:3.0.10.1567-ls183
    container_name: sonarr
    hostname: sonarr
    depends_on:
      - web
      - jackett
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/sonarr/data:/config
      - /home/tim/nas/media/sonarr/tvseries:/tv
      - /home/tim/nas/media/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - home-web
  
  radarr:
    image: linuxserver/radarr:nightly-4.6.1.7456-ls472
    container_name: radarr
    hostname: radarr
    depends_on:
      - web
      - jackett
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/radarr/data:/config
      - /home/tim/nas/media/radarr/movies:/movies
      - /home/tim/nas/media/transmission/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - home-web

  jackett:
    image: linuxserver/jackett:v0.21.258-ls111
    container_name: jackett
    hostname: jackett
    depends_on:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/tim/jackett/data:/config
      - /home/tim/nas/media/transmission/watch:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - home-web

  plex:
    image: linuxserver/plex:1.32.3.7162-b0a36929b-ls171
    container_name: plex
    hostname: plex
    network_mode: host
    depends_on:
      - web
      - sonarr
      - radarr
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/tim/plex/data:/config
      - /home/tim/nas/media/sonarr/tvseries:/tv
      - /home/tim/nas/media/radarr/movies:/movies
      - /tmp/transcoding:/tmp/transcoding
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:2023.05.2
    user: "0"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8380:80/tcp
    depends_on:
      - web
    environment:
      - TZ=Netherlands/Amsterdam
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=pihole.home
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - /home/tim/pihole/etc-pihole/:/etc/pihole/
      - /home/tim/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    networks:
      - home-web

networks:
  home-web:
